apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalilinux
  labels:
    app: kalilinux
spec:
  selector:
    matchLabels:
      app: kalilinux
  template:
    metadata:
      name: kalilinux
      labels:
        app: kalilinux
    spec:
      containers:
      - name: kalilinux-kali
        image: 'ilemonrain/kali-linux-sshd'
