apiVersion: v1
kind: Service
metadata:
  name: shell-in-a-box
  labels:
    app: shell-in-a-box
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 31487
  selector:
    app: shell-in-a-box

