apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-in-a-box
  namespace: lab-namespace
  labels:
    app: shell-in-a-box
spec:
  selector:
    matchLabels:
      app: shell-in-a-box
  template:
    metadata:
      name: shell-in-a-box
      labels:
        app: shell-in-a-box
    spec:
      containers:
        - name: shell-in-a-box
          image: 'sspreitzer/shellinabox:latest'
          env:
            - name: SIAB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: siab-pass
                  key: SIAB_PASSWORD
            - name: SIAB_SUDO
              valueFrom:
                configMapKeyRef:
                  name: siabsudo
                  key: SIAB_SUDO
 
